export type Product = {
  id: number
  name: string
  badge?: 'new' | 'best-seller'
  category: string
  material: string
  description: string
  image: string
  images?: string[]
  sizing: string
  colorScheme: string
  modelNumber: string
  topType: string
  finishing: string
  dateAdded?: string
  salesRank?: number
}

const BATCH1: Product[] = [
  {
    id: 1,
    name: 'The Calligraphy Throne',
    badge: 'best-seller',
    category: 'Coffee Tables',
    material: 'MDF + Fine Board (ZRK)',
    description: "Crafted from premium MDF and Fine Board (ZRK), The Calligraphy Throne is a masterpiece of artisanal precision. Its surface is finished in a striking combination of clean gloss, super black, and golden paint, all sealed beneath a silky matte lacquer that gives the piece its signature smooth, luminous touch. Presented in a rich chocolate brown finish, this table measures 48\" × 30\" × 17\" — proportioned to command any living space with quiet, sovereign authority.",
    image: '/images/1.webp',
    sizing: '48" × 30" × 17" (L × W × H)',
    colorScheme: 'Chocolate Brown',
    modelNumber: 'N2',
    topType: 'Clean Gloss + Super Black & Golden Paint',
    finishing: 'Silky Matte (Sealer + Lacquer)',
    dateAdded: '2026-05-10',
  },
  {
    id: 2,
    name: 'The Emerald Salon',
    badge: 'new',
    category: 'Coffee Tables',
    material: 'MDF + Fine Board (ZRK)',
    description: "Crafted from premium MDF and Fine Board (ZRK), The Emerald Salon is a refined statement of artisanal excellence. Its surface combines clean gloss, super black, and golden paint, all sealed beneath a silky matte lacquer for a smooth, luminous finish. Presented in a rich chocolate brown tone, this piece measures 48\" × 30\" × 17\" — perfectly proportioned to elevate any living space with understated luxury.",
    image: '/images/2.webp',
    sizing: '48" × 30" × 17" (L × W × H)',
    colorScheme: 'Chocolate Brown',
    modelNumber: 'N2',
    topType: 'Clean Gloss + Super Black & Golden Paint',
    finishing: 'Silky Matte (Sealer + Lacquer)',
    dateAdded: '2026-05-10',
  },
  {
    id: 3,
    name: 'The Imperial Arabesque',
    badge: 'best-seller',
    category: 'Coffee Tables',
    material: 'MDF + Fine Board (ZRK) with Imported Golden Foot',
    description: "Crafted from premium MDF and Fine Board (ZRK), The Imperial Arabesque is a sovereign statement of dark luxury. Its surface is finished in clean gloss with a super plain black paint treatment, all sealed beneath a brilliant high gloss lacquer for a commanding mirror-like depth. Standing on imported golden feet that add a striking contrast of warmth against the rich Royal Black finish, this table measures 42\" × 42\" × 18\" — a perfectly proportioned square silhouette that dominates any distinguished living space with quiet, regal authority.",
    image: '/images/3.webp',
    sizing: '42" × 42" × 18" (L × W × H)',
    colorScheme: 'Royal Golden',
    modelNumber: 'BB1',
    topType: 'Clean Gloss + Super Black Paint',
    finishing: 'High Gloss',
    dateAdded: '2026-05-10',
  },
  {
    id: 5,
    name: 'The Legacy Console',
    badge: 'best-seller',
    category: 'Coffee Tables',
    material: 'MDF + Fine Board (ZRK)',
    description: "Crafted from premium MDF and Fine Board (ZRK), The Legacy Console is a timeless piece of artisanal distinction. Its surface is finished in clean gloss with a super plain black paint treatment, all elevated beneath a brilliant high gloss lacquer that delivers a flawless, mirror-like sheen. Presented in a refined Off White & Black Duco finish, this table measures 60\" × 32\" × 19\" — generously proportioned to anchor any living space with quiet, enduring sophistication.",
    image: '/images/5.webp',
    sizing: '60" × 32" × 19" (L × W × H)',
    colorScheme: 'Off White & Black (Duco)',
    modelNumber: 'DD1',
    topType: 'Clean Gloss + Super Plain Black Paint',
    finishing: 'High Gloss',
    dateAdded: '2026-05-10',
  },
  {
    id: 6,
    name: 'The Imperial Marble',
    badge: 'best-seller',
    category: 'Coffee Tables',
    material: 'MDF + UV Sheet (ZRK)',
    description: "Crafted from premium MDF with a UV Sheet finish (ZRK), The Imperial Marble is a triumph of modern artisanal luxury. Its top surface features a stunning Marbelized UV Sheet that replicates the depth and elegance of natural marble with exceptional clarity. Finished in a radiant high gloss lacquer, the piece is presented in a sophisticated Off White & Golden palette with grey drawer detailing. Measuring 48\" × 30\" × 18\", this table brings timeless grandeur and refined proportion to any distinguished living space.",
    image: '/images/6.webp',
    sizing: '48" × 30" × 18" (L × W × H)',
    colorScheme: 'Off White & Golden with Grey Drawer',
    modelNumber: 'AA',
    topType: 'UV Sheet (Marbelized)',
    finishing: 'High Gloss',
    dateAdded: '2026-05-10',
  },
  {
    id: 7,
    name: 'The Noir Riviera',
    badge: 'best-seller',
    category: 'Coffee Tables',
    material: 'MDF + Fine Board (ZRK) with Imported Golden Foot',
    description: "Crafted from premium MDF and Fine Board (ZRK), The Noir Riviera is a statement of dark, sovereign luxury. Its surface is finished in clean gloss with a super black paint treatment, all sealed beneath a brilliant high gloss lacquer that delivers a commanding mirror-like depth. Standing on imported golden feet that add a striking contrast of warmth against the rich Royal Black finish, this table measures 48\" × 30\" × 17\" — a generously proportioned silhouette that anchors any distinguished living space with quiet, regal authority.",
    image: '/images/7.webp',
    sizing: '48" × 30" × 17" (L × W × H)',
    colorScheme: 'Royal Black',
    modelNumber: 'BB1',
    topType: 'Clean Gloss + Super Black Paint',
    finishing: 'High Gloss',
    dateAdded: '2026-05-10',
  },
  {
    id: 8,
    name: 'The Versailles Set',
    category: 'Coffee Tables',
    material: 'MDF + Fine Board (ZRK)',
    description: "Crafted from premium MDF and Fine Board (ZRK), The Versailles Set is a sophisticated three-piece collection built for the refined interior. The main coffee table — finished in a bold combination of clean gloss, super black, and golden paint — measures a generous 48\" (L) × 30\" (W) × 17\" (H), commanding any living space with quiet authority. Each matching side table, sized at 24\" × 24\" × 16.5\", echoes the same craftsmanship and proportions in perfect symmetry. Presented in a distinguished Grey and Jet Black colour scheme and sealed beneath a silky matte finish, the set delivers a luxurious surface that is as smooth to the touch as it is striking to the eye.",
    image: '/images/8.webp',
    sizing: 'Main: 48" × 30" × 17" · Side: 24" × 24" × 16.5"',
    colorScheme: 'Grey & Jet Black',
    modelNumber: 'V Versache',
    topType: 'Clean Gloss + Super Black & Golden Paint',
    finishing: 'Silky Matte',
    dateAdded: '2026-05-10',
  },
  {
    id: 9,
    name: 'The Urban Penthouse',
    badge: 'new',
    category: 'Coffee Tables',
    material: 'MDF + Fine Board (ZRK) with Solid Foot',
    description: "Crafted from premium MDF and Fine Board (ZRK) and set on a solid foot base, The Urban Penthouse is a bold expression of contemporary luxury. Its surface is finished in clean gloss with a super black paint treatment, sealed beneath a brilliant high gloss lacquer that delivers a commanding mirror-like depth. Presented in a refined Smoke Grey colour scheme, this table measures 48\" (L) × 30\" (W) × 17\" (H) — perfectly proportioned to anchor any modern living space with understated, architectural authority.",
    image: '/images/9.webp',
    sizing: '48" × 30" × 17" (L × W × H)',
    colorScheme: 'Smoke Grey',
    modelNumber: 'NW1',
    topType: 'Clean Gloss + Super Black Paint',
    finishing: 'High Gloss',
    dateAdded: '2026-05-10',
  },
  {
    id: 10,
    name: 'The Emperor Gold',
    badge: 'best-seller',
    category: 'Coffee Tables',
    material: 'MDF + Fine Board (ZRK) with Fiber Molding Piece & Classic Foot',
    description: "Crafted from premium MDF and Fine Board (ZRK), The Emperor Gold is adorned with intricate fiber molding pieces and set on a classic foot base — a masterwork of ornamental grandeur. Its surface is finished in clean gloss with super black and golden paint, sealed beneath a brilliant high gloss lacquer that delivers a commanding, mirror-like depth. Presented in an exclusive Imported Brazilian Royal Golden colour scheme, this table measures 48\" (L) × 30\" (W) × 18\" (H) — a sovereign centrepiece that commands reverence in any distinguished living space.",
    image: '/images/10.webp',
    sizing: '48" × 30" × 18" (L × W × H)',
    colorScheme: 'Imported Brazilian Royal Golden',
    modelNumber: 'NP',
    topType: 'Clean Gloss + Super Black & Golden Paint',
    finishing: 'High Gloss',
    dateAdded: '2026-05-10',
  },
  {
    id: 11,
    name: 'The Silver Requiem',
    category: 'Coffee Tables',
    material: 'MDF + Fine Board (ZRK) with Fiber Molding Foot',
    description: "Crafted from premium MDF and Fine Board (ZRK) and elevated on a sculptural fiber molding foot, The Silver Requiem is a masterpiece of dark, refined luxury. Its surface is finished in clean gloss with a super black paint treatment, sealed beneath a silky matte lacquer that gives the piece its signature smooth, luminous touch. Presented in a striking Jet Black and Silver colour scheme, this table measures 48\" (L) × 30\" (W) × 17\" (H) — a commanding presence for those who find beauty in darkness and elegance in contrast.",
    image: '/images/11.webp',
    sizing: '48" × 30" × 17" (L × W × H)',
    colorScheme: 'Jet Black & Silver',
    modelNumber: 'S9',
    topType: 'Clean Gloss + Super Black Paint',
    finishing: 'Silky Matte',
    dateAdded: '2026-05-10',
  },
  {
    id: 12,
    name: 'The Forest Baron',
    category: 'Coffee Tables',
    material: 'MDF + Fine Board (ZRK) with Classic Solid Foot',
    description: "Crafted from premium MDF and Fine Board (ZRK) and set on a classic solid foot base, The Forest Baron is a bold expression of understated luxury. Its surface is finished in clean gloss with a super black paint treatment, sealed beneath a brilliant high gloss lacquer that delivers a commanding, mirror-like depth. Presented in a refined Smoke Grey colour scheme, this table measures 48\" (L) × 30\" (W) × 17\" (H) — perfectly proportioned to anchor any modern living space with quiet, architectural authority.",
    image: '/images/12.webp',
    sizing: '48" × 30" × 17" (L × W × H)',
    colorScheme: 'Smoke Grey',
    modelNumber: 'B7',
    topType: 'Clean Gloss + Super Black Paint',
    finishing: 'High Gloss',
    dateAdded: '2026-05-10',
  },
  {
    id: 13,
    name: 'The Maharaja',
    category: 'Coffee Tables',
    material: 'MDF (ZRK) with Imported Golden Chrome Foot',
    description: "Crafted from premium MDF (ZRK) and elevated on imported golden chrome feet, The Maharaja is a regal statement of refined luxury. Its surface is finished in clean gloss with super black and off white high gloss border paint, sealed beneath a brilliant high gloss lacquer that delivers a flawless, commanding depth. Presented in a distinguished Off White High Gloss colour scheme, this table measures 48\" (L) × 30\" (W) × 17\" (H) — a sovereign centrepiece that brings timeless elegance and architectural grace to any distinguished living space.",
    image: '/images/13.webp',
    sizing: '48" × 30" × 17" (L × W × H)',
    colorScheme: 'Off White High Gloss',
    modelNumber: 'M1',
    topType: 'Clean Gloss + Super Black & Off White High Gloss Border Paint',
    finishing: 'High Gloss',
    dateAdded: '2026-05-10',
  },
  {
    id: 14,
    name: 'The Alabaster Night',
    category: 'Coffee Tables',
    material: 'MDF + Fine Board (ZRK)',
    description: "Crafted from premium MDF and Fine Board (ZRK), The Alabaster Night is a study in dark, refined sophistication. Its surface is finished in clean gloss with a super black paint treatment, sealed beneath a silky matte lacquer that delivers a smooth, luminous touch. Presented in a sleek Smoke Grey colour scheme, this table measures 48\" (L) × 30\" (W) × 16.5\" (H) — a quietly commanding presence that brings understated elegance and contemporary authority to any distinguished living space.",
    image: '/images/14.webp',
    sizing: '48" × 30" × 16.5" (L × W × H)',
    colorScheme: 'Smoke Grey',
    modelNumber: 'BG1',
    topType: 'Clean Gloss + Super Black Paint',
    finishing: 'Silky Matte',
    dateAdded: '2026-05-10',
  },
  {
    id: 16,
    name: 'The Ivory Shadow',
    category: 'Coffee Tables',
    material: 'MDF + Fine Board (ZRK) with Fiber Molding Classic Foot',
    description: "Crafted from premium MDF and Fine Board (ZRK) and elevated on a fiber molding classic foot, The Ivory Shadow is a masterwork of warmth and ornamental refinement. Its surface is finished in clean gloss with a super black and golden paint treatment, sealed beneath a silky matte lacquer that delivers the piece's signature smooth, luminous touch. Presented in a rich Sheesham tone with hand-applied imported golden accents, this table measures 48\" (L) × 30\" (W) × 17\" (H) — a sovereignly crafted centrepiece that brings heritage warmth and artisanal grandeur to any distinguished living space.",
    image: '/images/16.webp',
    sizing: '48" × 30" × 17" (L × W × H)',
    colorScheme: 'Sheesham & Hand Applied Imported Golden',
    modelNumber: 'S92',
    topType: 'Clean Gloss + Super Black & Golden Paint',
    finishing: 'Silky Matte',
    dateAdded: '2026-05-10',
  },
  {
    id: 17,
    name: 'The Duet',
    category: 'Coffee Tables',
    material: 'MDF + Fine Board (ZRK) with Solid Foot + Antique Gold Finish',
    description: "Crafted from premium MDF and Fine Board (ZRK) and set on a solid foot with an antique gold finish, The Duet is a masterpiece of warmth and timeless refinement. Its surface is dressed in a clean gloss treatment, sealed beneath a silky matte lacquer for a smooth, distinguished touch. Both the top and sides carry a hand-applied antique gold rubbing finish that brings an aged, aristocratic warmth to every surface. Measuring 48\" (L) × 30\" (W) × 17\" (H), this table is a quietly sovereign centrepiece — one that elevates any living space with the understated grandeur of heritage craftsmanship.",
    image: '/images/17.webp',
    sizing: '48" × 30" × 17" (L × W × H)',
    colorScheme: 'Top & Sides Antique Gold Rubbing Finish & Brown',
    modelNumber: 'FT',
    topType: 'Clean Gloss',
    finishing: 'Silky Matte',
    dateAdded: '2026-05-10',
  },
  {
    id: 18,
    name: 'The Golden Heritage',
    category: 'Coffee Tables',
    material: 'MDF + CNC Carving (ZRK) with Solid Legs',
    description: "Crafted from premium MDF with intricate CNC carving (ZRK) and set on solid legs, The Golden Heritage is a masterwork of artisanal precision and ornamental grandeur. Its surface is dressed in a clean gloss treatment, sealed beneath a silky matte lacquer for a smooth, distinguished touch. Presented in a rich Brown and Golden colour scheme, this table measures 48\" (L) × 30\" (W) × 17\" (H) — a sovereignly crafted centrepiece that brings heritage warmth and carved artistry to any distinguished living space.",
    image: '/images/18.webp',
    sizing: '48" × 30" × 17" (L × W × H)',
    colorScheme: 'Brown & Golden',
    modelNumber: 'Victoria',
    topType: 'Clean Gloss',
    finishing: 'Silky Matte',
    dateAdded: '2026-05-10',
  },
  {
    id: 19,
    name: 'The Navy Atelier',
    category: 'Coffee Tables',
    material: 'MDF + CNC Carving (ZRK) with Solid Legs',
    description: "Crafted from premium MDF with intricate CNC carving (ZRK) and set on solid legs, The Navy Atelier is a bold expression of ornamental luxury. Its surface is finished in a clean gloss treatment, sealed beneath a brilliant high gloss lacquer that delivers a commanding, mirror-like depth. Presented in a striking Royal Gold and Antique Golden colour scheme, this table measures 48\" (L) × 30\" (W) × 17\" (H) — a sovereignly crafted centrepiece that commands reverence in any distinguished living space.",
    image: '/images/19.webp',
    sizing: '48" × 30" × 17" (L × W × H)',
    colorScheme: 'Royal Gold & Antique Golden',
    modelNumber: 'SS',
    topType: 'Clean Gloss',
    finishing: 'High Gloss',
    dateAdded: '2026-05-10',
  },
  {
    id: 20,
    name: 'The Versailles Set II',
    badge: 'new',
    category: 'Coffee Tables',
    material: 'MDF + CNC Tree Motive (ZRK)',
    description: "Crafted from premium MDF with an intricate CNC tree motive (ZRK), The Versailles Set II is a masterpiece of nature-inspired artisanal carving. Its surface is dressed in a clean gloss treatment, sealed beneath a silky matte lacquer for a smooth, distinguished touch. Presented in a rich Chocolate Brown colour scheme, this table measures 48\" (L) × 30\" (W) × 17\" (H) — a sovereignly crafted centrepiece that brings organic warmth and carved artistry to any distinguished living space.",
    image: '/images/20.webp',
    sizing: '48" × 30" × 17" (L × W × H)',
    colorScheme: 'Chocolate Brown',
    modelNumber: 'RT',
    topType: 'Clean Gloss',
    finishing: 'Silky Matte',
    dateAdded: '2026-05-10',
  },
  {
    id: 21,
    name: 'The Sovereign Set',
    badge: 'best-seller',
    category: 'Coffee Tables',
    material: 'MDF + CNC With Silk Fabric (ZRK)',
    description: "Crafted from premium MDF with intricate CNC flower carving and sumptuous silk fabric detailing (ZRK), The Sovereign Set is a masterwork of ornamental refinement and tactile luxury. Its surface is dressed in a clean gloss treatment, sealed beneath a silky matte lacquer for a smooth, distinguished touch. Presented in a rich Chocolate Brown colour scheme, this piece measures 48\" (L) × 30\" (W) × 17\" (H) — a sovereignly crafted centrepiece that brings heritage warmth, carved artistry, and silk elegance to any distinguished living space.",
    image: '/images/21.webp',
    sizing: '48" × 30" × 17" (L × W × H)',
    colorScheme: 'Chocolate Brown',
    modelNumber: 'RT',
    topType: 'Clean Gloss',
    finishing: 'Silky Matte',
    dateAdded: '2026-05-10',
  },
  {
    id: 22,
    name: 'The Marble Throne',
    category: 'Coffee Tables',
    material: 'MDF + Fine Board (ZRK) with Fiber Molding Foot',
    description: "Crafted from premium MDF and Fine Board (ZRK) and elevated on a sculptural fiber molding foot, The Marble Throne is a masterpiece of dark, refined luxury. Its surface is finished in clean gloss with a super black paint treatment, sealed beneath a silky matte lacquer that gives the piece its signature smooth, luminous touch. Presented in a striking Jet Black and Silver colour scheme, this table measures 48\" (L) × 30\" (W) × 17\" (H) — a commanding presence for those who find beauty in darkness and elegance in contrast.",
    image: '/images/22.webp',
    sizing: '48" × 30" × 17" (L × W × H)',
    colorScheme: 'Jet Black & Silver',
    modelNumber: 'S9',
    topType: 'Clean Gloss + Super Black Paint',
    finishing: 'Silky Matte',
    dateAdded: '2026-05-10',
  },
  {
    id: 23,
    name: 'The Obsidian Baron',
    category: 'Coffee Tables',
    material: 'MDF + Fine Board (ZRK) with Solid Foot',
    description: "Crafted from premium MDF and Fine Board (ZRK) and set on a solid foot base, The Obsidian Baron is a bold expression of contemporary luxury. Its surface is finished in clean gloss with a super black paint treatment, sealed beneath a brilliant high gloss lacquer that delivers a commanding mirror-like depth. Presented in a refined Smoke Grey colour scheme, this table measures 48\" (L) × 30\" (W) × 17\" (H) — perfectly proportioned to anchor any modern living space with understated, architectural authority.",
    image: '/images/23.webp',
    sizing: '48" × 30" × 17" (L × W × H)',
    colorScheme: 'Smoke Grey',
    modelNumber: 'NW1',
    topType: 'Clean Gloss + Super Black Paint',
    finishing: 'High Gloss',
    dateAdded: '2026-05-10',
  },
  {
    id: 24,
    name: 'The Oval Reeded',
    badge: 'new',
    category: 'Coffee Tables',
    material: 'MDF + Fine Board (ZRK)',
    description: "Crafted from premium MDF and Fine Board (ZRK), The Oval Reeded is a refined four-stool coffee table set built for both elegance and everyday living. Its MDF top surface is sealed beneath a silky matte lacquer that delivers a smooth, distinguished finish. Presented in a sophisticated Two Tone Brown colour scheme, this set measures 42\" (L) × 42\" (W) × 18\" (H) — a perfectly proportioned square silhouette that brings warmth, versatility, and artisanal character to any distinguished living space.",
    image: '/images/24.webp',
    sizing: '42" × 42" × 18" (L × W × H)',
    colorScheme: 'Two Tone Brown',
    modelNumber: '4 Stools Coffee Table',
    topType: 'MDF',
    finishing: 'Silky Matte',
    dateAdded: '2026-05-10',
  },
  {
    id: 25,
    name: 'The Sovereign Set II',
    category: 'Coffee Tables',
    material: 'MDF + Fine Board (ZRK)',
    description: "Crafted from premium MDF and Fine Board (ZRK), The Sovereign Set II is a bold statement of dark, contemporary luxury. Its surface is dressed in a clean gloss treatment, sealed beneath a brilliant high gloss lacquer that delivers a commanding, mirror-like depth. Presented in a striking Jet Black and Golden Drawer colour scheme, this piece measures 48\" (L) × 30\" (W) × 17\" (H) — a sovereignly crafted centrepiece that brings dramatic contrast and refined elegance to any distinguished living space.",
    image: '/images/25.webp',
    sizing: '48" × 30" × 17" (L × W × H)',
    colorScheme: 'Jet Black & Golden Drawer',
    modelNumber: 'B2',
    topType: 'Clean Gloss',
    finishing: 'High Gloss',
    dateAdded: '2026-05-10',
  },
  {
    id: 26,
    name: 'The Timber Oval',
    category: 'Coffee Tables',
    material: 'MDF (ZRK) with Imported Chrome Gold Foot',
    description: "Crafted from premium MDF (ZRK) and elevated on imported chrome gold feet, The Timber Oval is a striking expression of modern luxury. Its top surface features a stunning white marbelized high gloss finish that replicates the depth and elegance of natural marble with exceptional clarity. Presented in a refined Swik and White Duco colour scheme, this table measures 48\" (L) × 30\" (W) × 18\" (H) — perfectly proportioned to command any distinguished living space with timeless grandeur and polished sophistication.",
    image: '/images/26.webp',
    sizing: '48" × 30" × 18" (L × W × H)',
    colorScheme: 'Swik & White (Duco)',
    modelNumber: 'Round.C',
    topType: 'White Marbelized High Gloss',
    finishing: 'High Gloss',
    dateAdded: '2026-05-10',
  },
  {
    id: 27,
    name: 'The Sovereign Set V',
    badge: 'new',
    category: 'Coffee Tables',
    material: 'MDF + Fine Board (ZRK) with Fiber Molding Golden Foot',
    description: "Crafted from premium MDF and Fine Board (ZRK) and elevated on ornate fiber molding golden feet, The Sovereign Set V is a bold declaration of dark, regal luxury. Its surface is finished in clean gloss with a super black paint treatment, sealed beneath a brilliant high gloss lacquer that delivers a commanding, mirror-like depth. Presented in a striking Royal Golden and Jet Black Duco colour scheme, this piece measures 48\" (L) × 30\" (W) × 17\" (H) — a sovereignly crafted centrepiece that commands reverence and brings dramatic grandeur to any distinguished living space.",
    image: '/images/27.webp',
    sizing: '48" × 30" × 17" (L × W × H)',
    colorScheme: 'Royal Golden & Jet Black (Duco)',
    modelNumber: 'Double TT',
    topType: 'Clean Gloss + Super Black Paint',
    finishing: 'High Gloss',
    dateAdded: '2026-05-10',
  },
  {
    id: 28,
    name: 'The Cream Oval',
    category: 'Coffee Tables',
    material: 'MDF + Fine Board (ZRK)',
    description: "Crafted from premium MDF and Fine Board (ZRK), The Cream Oval is a refined expression of contemporary sophistication. Its surface is finished in clean gloss with a grey and super black paint treatment, sealed beneath a silky matte lacquer that delivers the piece's signature smooth, luminous touch. Presented in an elegant Smoke Grey Duco colour scheme, this table measures 48\" (L) × 30\" (W) × 17\" (H) — perfectly proportioned to bring understated elegance and quiet architectural authority to any distinguished living space.",
    image: '/images/28.webp',
    sizing: '48" × 30" × 17" (L × W × H)',
    colorScheme: 'Smoke Grey (Duco)',
    modelNumber: 'C2',
    topType: 'Clean Gloss + Grey & Super Black Paint',
    finishing: 'Silky Matte',
    dateAdded: '2026-05-10',
  },
  {
    id: 30,
    name: 'The Silver Salon',
    badge: 'new',
    category: 'Coffee Tables',
    material: 'MDF (ZRK) with Fiber Molding Foot',
    description: "Crafted from premium MDF (ZRK) and elevated on a sculptural fiber molding foot, The Silver Salon is a bold expression of dark, contemporary luxury. Its surface is finished in clean gloss with a super black paint treatment, sealed beneath a brilliant high gloss lacquer that delivers a commanding, mirror-like depth. Presented in a distinguished Grey and Black Antique Duco colour scheme, this piece measures 48\" (L) × 30\" (W) × 17\" (H) — perfectly proportioned to anchor any distinguished living space with understated architectural authority and refined elegance.",
    image: '/images/30.webp',
    sizing: '48" × 30" × 17" (L × W × H)',
    colorScheme: 'Grey & Black Antique (Duco)',
    modelNumber: 'FFN',
    topType: 'Clean Gloss + Super Black Paint',
    finishing: 'High Gloss',
    dateAdded: '2026-05-15',
    salesRank: 5,
  },
]

const BATCH2: Product[] = [
  {
    id: 31,
    name: 'The Pearl Regent',
    badge: 'new',
    category: 'Coffee Tables',
    material: 'MDF (ZRK) with Fiber Molding Hand Applied Golden Foot',
    description: "Crafted from premium MDF (ZRK) and elevated on an ornate fiber molding foot with hand-applied golden detailing, The Pearl Regent is a regal statement of refined luxury. Its surface is finished in clean gloss with a super black paint treatment, sealed beneath a brilliant high gloss lacquer that delivers a flawless, commanding depth. Presented in a distinguished Off White and Black Antique Duco colour scheme, this table measures 48\" (L) × 30\" (W) × 17\" (H) — a sovereignly crafted centrepiece that brings timeless elegance and artisanal grandeur to any distinguished living space.",
    image: '/images/31.webp',
    sizing: '48" × 30" × 17" (L × W × H)',
    colorScheme: 'Off White & Black Antique (Duco)',
    modelNumber: 'WB1',
    topType: 'Clean Gloss + Super Black Paint',
    finishing: 'High Gloss',
    dateAdded: '2026-05-15',
    salesRank: 2,
  },
  {
    id: 32,
    name: 'The Ivory Drum',
    badge: 'new',
    category: 'Coffee Tables',
    material: 'White Reeded Drum Body & Polished Black Glass Top with Gold Ring Legs',
    description: "A bold round drum silhouette entirely wrapped in fine white reeding, topped with a polished black glass surface and elevated on slender polished gold ring legs. The Ivory Drum brings organic, sculptural form to the luxury living room — a piece that invites touch and rewards every viewing angle with a new moment of beauty.",
    image: '/images/32.webp',
    sizing: '90 cm Diameter × 45 cm H',
    colorScheme: 'White Reeded, Black Glass, Gold',
    modelNumber: '',
    topType: 'Polished Black Glass',
    finishing: 'High Gloss',
    dateAdded: '2026-05-15',
    salesRank: 4,
  },
  {
    id: 33,
    name: 'The Latte Luxe',
    badge: 'new',
    category: 'Coffee Tables',
    material: 'MDF (ZRK) with Imported Golden Chrome Foot',
    description: "Crafted from premium MDF (ZRK) and elevated on imported golden chrome feet, The Latte Luxe is a striking expression of contemporary luxury. Its surface is finished in clean gloss with a super black paint treatment, sealed beneath a brilliant high gloss lacquer that delivers a commanding, mirror-like depth. Presented in an exclusive Metallic Champion Duco colour scheme, this table measures 48\" (L) × 30\" (W) × 17\" (H) — perfectly proportioned to anchor any distinguished living space with understated glamour and sovereign authority.",
    image: '/images/33.webp',
    sizing: '48" × 30" × 17" (L × W × H)',
    colorScheme: 'Metallic Champion (Duco)',
    modelNumber: '4D',
    topType: 'Clean Gloss + Super Black Paint',
    finishing: 'High Gloss',
    dateAdded: '2026-05-15',
    salesRank: 7,
  },
  {
    id: 34,
    name: 'The Phantom Steel',
    badge: 'new',
    category: 'Coffee Tables',
    material: 'MDF (ZRK) with Fiber Molding Hand Applied Golden Foot',
    description: "Crafted from premium MDF (ZRK) and elevated on an ornate fiber molding foot with hand-applied golden detailing, The Phantom Steel is a bold expression of dark, contemporary luxury. Its surface is finished in clean gloss with a super black paint treatment, sealed beneath a brilliant high gloss lacquer that delivers a commanding, mirror-like depth. Presented in an exclusive Metallic Dark Grey Duco colour scheme, this table measures 48\" (L) × 30\" (W) × 17\" (H) — perfectly proportioned to anchor any distinguished living space with understated power and sovereign authority.",
    image: '/images/34.webp',
    sizing: '48" × 30" × 17" (L × W × H)',
    colorScheme: 'Metallic Dark Grey (Duco)',
    modelNumber: 'WB2',
    topType: 'Clean Gloss + Super Black Paint',
    finishing: 'High Gloss',
    dateAdded: '2026-05-15',
    salesRank: 9,
  },
  {
    id: 35,
    name: 'The Twilight',
    badge: 'new',
    category: 'Coffee Tables',
    material: 'MDF (ZRK) with Solid Foot Swick Paint',
    description: "Crafted from premium MDF (ZRK) and set on a solid foot with a distinctive swick paint finish, The Twilight is a bold expression of dark, contemporary luxury. Its surface is finished in clean gloss with a super black paint treatment, sealed beneath a brilliant high gloss lacquer that delivers a commanding, mirror-like depth. Presented in a striking Black and Swick Metallic Duco colour scheme, this table measures 48\" (L) × 30\" (W) × 17\" (H) — perfectly proportioned to anchor any distinguished living space with dramatic elegance and sovereign authority.",
    image: '/images/35.webp',
    sizing: '48" × 30" × 17" (L × W × H)',
    colorScheme: 'Black & Swick Metallic (Duco)',
    modelNumber: 'Aroma',
    topType: 'Clean Gloss + Super Black Paint',
    finishing: 'High Gloss',
    dateAdded: '2026-05-15',
    salesRank: 6,
  },
  {
    id: 36,
    name: 'The Grand Salon',
    badge: 'new',
    category: 'Coffee Tables',
    material: 'MDF (ZRK) with Imported Golden Chrome Foot',
    description: "Crafted from premium MDF (ZRK) and elevated on imported golden chrome feet, The Grand Salon is a regal expression of opulent contemporary luxury. Its surface is finished in clean gloss with a super black paint treatment, sealed beneath a brilliant high gloss lacquer that delivers a commanding, mirror-like depth. Presented in a stunning Royal Gold Duco colour scheme, this table measures 48\" (L) × 30\" (W) × 17\" (H) — perfectly proportioned to anchor any distinguished living space with timeless grandeur and sovereign authority.",
    image: '/images/36.webp',
    sizing: '48" × 30" × 17" (L × W × H)',
    colorScheme: 'Royal Gold (Duco)',
    modelNumber: 'SDD',
    topType: 'Clean Gloss + Super Black Paint',
    finishing: 'High Gloss',
    dateAdded: '2026-05-15',
    salesRank: 1,
  },
  {
    id: 37,
    name: 'The Golden Baroque Trio',
    badge: 'new',
    category: 'Coffee Sets',
    material: 'MDF (ZRK) with Fiber Molding Foot — 3-Piece Set',
    description: "Crafted from premium MDF (ZRK) and elevated on ornate fiber molding feet, The Golden Baroque Trio is a magnificent three-piece set built for the grandest of interiors. Each piece is finished in clean gloss with a super black and golden paint treatment, sealed beneath a brilliant high gloss lacquer that delivers a commanding, mirror-like depth. Presented in a regal Royal Golden Antique Duco colour scheme, the main table measures 42\" (L) × 42\" (W) × 18\" (H) while the two matching side tables each measure 24\" (L) × 24\" (W) × 17\" (H) — a sovereignly crafted ensemble that transforms any distinguished living space into a salon of extraordinary grandeur.",
    image: '/images/37.webp',
    sizing: 'Main: 42" × 42" × 18" · Side: 24" × 24" × 17"',
    colorScheme: 'Royal Golden Antique (Duco)',
    modelNumber: 'FP1 Set',
    topType: 'Clean Gloss + Super Black & Golden Paint',
    finishing: 'High Gloss',
    dateAdded: '2026-05-15',
    salesRank: 8,
  },
  {
    id: 38,
    name: 'The Ivory Stripes',
    badge: 'new',
    category: 'Coffee Tables',
    material: 'MDF (ZRK) with Fiber Molding Foot',
    description: "Crafted from premium MDF (ZRK) and elevated on an ornate fiber molding foot, The Ivory Stripes is a refined expression of elegant contrast and artisanal luxury. Its surface is finished in clean gloss with a super black paint treatment, sealed beneath a brilliant high gloss lacquer that delivers a commanding, mirror-like depth. Presented in a distinguished Off White and Golden Voinal Duco colour scheme, this table measures 48\" (L) × 30\" (W) × 17\" (H) — perfectly proportioned to anchor any distinguished living space with timeless sophistication and sovereign authority.",
    image: '/images/38.webp',
    sizing: '48" × 30" × 17" (L × W × H)',
    colorScheme: 'Off White & Golden Voinal (Duco)',
    modelNumber: 'WB3',
    topType: 'Clean Gloss + Super Black Paint',
    finishing: 'High Gloss',
    dateAdded: '2026-05-15',
    salesRank: 11,
  },
  {
    id: 39,
    name: 'The Champagne Salon',
    badge: 'new',
    category: 'Coffee Tables',
    material: 'MDF (ZRK) with Imported Golden Foot',
    description: "Crafted from premium MDF (ZRK) and elevated on imported golden feet, The Champagne Salon is a refined expression of contemporary opulence. Featuring a practical double drawer design, its surface is finished in clean gloss with a super black paint treatment, sealed beneath a brilliant high gloss lacquer that delivers a commanding, mirror-like depth. Presented in an exclusive Golden Swick Duco colour scheme, this table measures 48\" (L) × 30\" (W) × 17\" (H) — perfectly proportioned to anchor any distinguished living space with understated glamour and sovereign authority.",
    image: '/images/39.webp',
    sizing: '48" × 30" × 17" (L × W × H)',
    colorScheme: 'Golden Swick (Duco)',
    modelNumber: 'KK with Double Drawer',
    topType: 'Clean Gloss + Super Black Paint',
    finishing: 'High Gloss',
    dateAdded: '2026-05-15',
    salesRank: 10,
  },
  {
    id: 40,
    name: 'The Bicolour Horizon',
    badge: 'new',
    category: 'Coffee Tables',
    material: 'MDF (ZRK) with Imported Golden Chrome Foot',
    description: "Crafted from premium MDF (ZRK) and elevated on imported golden chrome feet, The Bicolour Horizon is a bold expression of contemporary luxury. Its surface is finished in clean gloss with a super black paint treatment, sealed beneath a brilliant high gloss lacquer that delivers a commanding, mirror-like depth. Presented in a refined Smoked Grey Duco colour scheme, this table measures 48\" (L) × 30\" (W) × 17\" (H) — perfectly proportioned to anchor any distinguished living space with understated sophistication and sovereign authority.",
    image: '/images/40.webp',
    sizing: '48" × 30" × 17" (L × W × H)',
    colorScheme: 'Smoked Grey (Duco)',
    modelNumber: 'SDD3',
    topType: 'Clean Gloss + Super Black Paint',
    finishing: 'High Gloss',
    dateAdded: '2026-05-15',
    salesRank: 12,
  },
  {
    id: 41,
    name: 'The Grey Talon',
    badge: 'new',
    category: 'Coffee Tables',
    material: 'MDF (ZRK) with Solid Foot',
    description: "Crafted from premium MDF (ZRK) and set on a solid foot base, The Grey Talon is a striking expression of modern luxury. Its top surface features a stunning high gloss marbelized finish that replicates the depth and elegance of natural marble with exceptional clarity, sealed beneath a brilliant high gloss lacquer for a flawless, commanding sheen. Presented in a sophisticated Off White and Smoke Grey Duco colour scheme, this table measures 48\" (L) × 30\" (W) × 17\" (H) — perfectly proportioned to anchor any distinguished living space with timeless grandeur and refined sophistication.",
    image: '/images/41.webp',
    sizing: '48" × 30" × 17" (L × W × H)',
    colorScheme: 'Off White & Smoke Grey (Duco)',
    modelNumber: 'TGT',
    topType: 'High Gloss Marbelized',
    finishing: 'High Gloss',
    dateAdded: '2026-05-15',
    salesRank: 14,
  },
  {
    id: 43,
    name: 'The Haussmann Grand',
    badge: 'new',
    category: 'Coffee Tables',
    material: 'MDF (ZRK) with Imported Golden Foot',
    description: "Crafted from premium MDF (ZRK) and elevated on imported golden feet, The Haussmann Grand is a masterwork of marble-inspired grandeur. Featuring a convenient double drawer design, its top surface showcases a stunning UV Golden Marbelized finish that replicates the depth and elegance of natural marble with exceptional clarity, sealed beneath a UV high gloss lacquer for a flawless, luminous sheen. Presented in an exquisite White and Gold Voilan Duco colour scheme, this table measures 48\" (L) × 30\" (W) × 17\" (H) — a sovereignly crafted centrepiece that commands timeless elegance and refined grandeur in any distinguished living space.",
    image: '/images/43.webp',
    sizing: '48" × 30" × 17" (L × W × H)',
    colorScheme: 'White & Gold Voilan (Duco)',
    modelNumber: 'KK4 with Double Drawer',
    topType: 'UV Golden Marbelized',
    finishing: 'UV High Gloss',
    dateAdded: '2026-05-15',
    salesRank: 16,
  },
  {
    id: 44,
    name: 'The Silver Duke',
    badge: 'new',
    category: 'Coffee Tables',
    material: 'MDF (ZRK) with Fiber Molding Foot',
    description: "Crafted from premium MDF (ZRK) and elevated on an ornate fiber molding foot, The Silver Duke is a bold declaration of monochrome luxury. Its surface is finished in clean gloss with a super black paint treatment, sealed beneath a brilliant high gloss lacquer that delivers a commanding, mirror-like depth. Presented in a striking Metallic Silver and Jet Black Duco colour scheme, this table measures 48\" (L) × 30\" (W) × 17\" (H) — perfectly proportioned to anchor any distinguished living space with dramatic contrast, contemporary edge, and sovereign authority.",
    image: '/images/44.webp',
    sizing: '48" × 30" × 17" (L × W × H)',
    colorScheme: 'Metallic Silver & Jet Black (Duco)',
    modelNumber: 'SD1',
    topType: 'Clean Gloss + Super Black Paint',
    finishing: 'High Gloss',
    dateAdded: '2026-05-15',
    salesRank: 15,
  },
]

const BATCH3: Product[] = [
  {
    id: 46,
    name: 'The Mughal Trio',
    badge: 'new',
    category: 'Coffee Sets',
    material: 'MDF + Fine Board (ZRK)',
    description: "Crafted from premium MDF and Fine Board (ZRK), The Mughal Trio is a masterwork of ornamental grandeur and artisanal refinement. Its surface is finished in clean gloss with a super black and golden paint treatment, sealed beneath a silky matte lacquer that delivers the piece's signature smooth, luminous touch. Featuring an exquisite golden double drawer, this table is presented in a rich Chocolate Brown and Golden Duco colour scheme and measures 48\" (L) × 30\" (W) × 17\" (H) — a sovereignly crafted centrepiece that brings heritage warmth, golden artistry, and distinguished elegance to any living space.",
    image: '/images/46.webp',
    sizing: '48" × 30" × 17" (L × W × H)',
    colorScheme: 'Chocolate Brown & Golden (Duco)',
    modelNumber: 'TMT with Golden Double Drawer',
    topType: 'Clean Gloss + Super Black & Golden Paint',
    finishing: 'Silky Matte',
    dateAdded: '2026-05-17',
    salesRank: 5,
  },
  {
    id: 47,
    name: 'The Fleur Noir',
    badge: 'new',
    category: 'Coffee Tables',
    material: 'MDF + Fine Board (ZRK)',
    description: "Crafted from premium MDF and Fine Board (ZRK), The Fleur Noir is a bold expression of dark, artisanal luxury. Its surface is finished in clean gloss with a hand-applied golden and super black paint treatment, sealed beneath a brilliant high gloss lacquer that delivers a commanding, mirror-like depth. Presented in a rich Chocolate Brown Duco colour scheme, this table measures 48\" (L) × 30\" (W) × 17\" (H) — perfectly proportioned to anchor any distinguished living space with understated elegance and sovereign authority.",
    image: '/images/47.webp',
    sizing: '48" × 30" × 17" (L × W × H)',
    colorScheme: 'Chocolate Brown (Duco)',
    modelNumber: 'TFN',
    topType: 'Clean Gloss + Hand Applied Golden & Super Black Paint',
    finishing: 'High Gloss',
    dateAdded: '2026-05-17',
    salesRank: 7,
  },
  {
    id: 48,
    name: 'The Noir Strata',
    badge: 'new',
    category: 'Coffee Tables',
    material: 'MDF + Fine Board (ZRK)',
    description: "Crafted from premium MDF and Fine Board (ZRK), The Noir Strata is a refined expression of dark, artisanal sophistication. Its surface is finished in clean gloss with a golden and super black paint treatment, sealed beneath a silky matte lacquer that delivers the piece's signature smooth, luminous touch. Presented in a rich Chocolate Brown Duco colour scheme, this table measures 48\" (L) × 30\" (W) × 17\" (H) — perfectly proportioned to anchor any distinguished living space with understated elegance and quiet sovereign authority.",
    image: '/images/48.webp',
    sizing: '48" × 30" × 17" (L × W × H)',
    colorScheme: 'Chocolate Brown (Duco)',
    modelNumber: 'TNS',
    topType: 'Clean Gloss + Golden & Super Black Paint',
    finishing: 'Silky Matte',
    dateAdded: '2026-05-17',
    salesRank: 6,
  },
  {
    id: 49,
    name: 'The Obsidian Bloom',
    badge: 'new',
    category: 'Coffee Sets',
    material: 'MDF + Fine Board (ZRK) with Fiber Molding Solid Foot Antique Gold',
    description: "Crafted from premium MDF and Fine Board (ZRK) and elevated on ornate fiber molding solid feet with an antique gold finish, The Obsidian Bloom is a masterwork of warmth and ornamental refinement. Its surface is finished in clean gloss with a super black and golden paint treatment, sealed beneath a silky matte lacquer that delivers the piece's signature smooth, luminous touch. Presented in a rich Chocolate Brown Duco colour scheme, the main coffee table measures 48\" (L) × 30\" (W) × 17\" (H) while the two matching side tables each measure 24\" (L) × 24\" (W) × 16\" (H) — a sovereignly crafted three-piece ensemble that brings heritage warmth, golden artistry, and distinguished elegance to any living space.",
    image: '/images/49.webp',
    sizing: 'Main: 48" × 30" × 17" · Side: 24" × 24" × 16"',
    colorScheme: 'Chocolate Brown (Duco)',
    modelNumber: 'OB1',
    topType: 'Clean Gloss + Super Black & Golden Paint',
    finishing: 'Silky Matte',
    dateAdded: '2026-05-17',
    salesRank: 9,
  },
  {
    id: 50,
    name: 'The Royal Lotus',
    badge: 'new',
    category: 'Coffee Tables',
    material: 'MDF + Fine Board (ZRK)',
    description: "Crafted from premium MDF and Fine Board (ZRK), The Royal Lotus is a refined expression of dark, artisanal luxury. Its surface is finished in clean gloss with a super black paint treatment, sealed beneath a silky matte lacquer that delivers the piece's signature smooth, luminous touch. Presented in a rich Chocolate Brown Duco colour scheme, this table measures 48\" (L) × 30\" (W) × 17\" (H) — perfectly proportioned to anchor any distinguished living space with understated elegance and sovereign authority.",
    image: '/images/50.webp',
    sizing: '48" × 30" × 17" (L × W × H)',
    colorScheme: 'Chocolate Brown (Duco)',
    modelNumber: 'TRL',
    topType: 'Clean Gloss + Super Black Paint',
    finishing: 'Silky Matte',
    dateAdded: '2026-05-17',
    salesRank: 2,
  },
  {
    id: 51,
    name: 'The Grand Vizier',
    badge: 'new',
    category: 'Coffee Sets',
    material: 'MDF + Fine Board (ZRK)',
    description: "Crafted from premium MDF and Fine Board (ZRK), The Grand Vizier is a bold statement of dark, sovereign luxury. Its surface is finished in clean gloss with a super black and golden paint treatment, sealed beneath a brilliant high gloss lacquer that delivers a commanding, mirror-like depth. Presented in a rich Chocolate Brown Duco colour scheme, the main coffee table is proportioned as a refined square measuring 36\" (L) × 36\" (W) × 17\" (H), accompanied by two matching side tables each measuring 24\" (L) × 24\" (W) × 16\" (H) — a sovereignly crafted three-piece ensemble that commands reverence and brings dramatic grandeur to any distinguished living space.",
    image: '/images/51.webp',
    sizing: 'Main: 36" × 36" × 17" · Side: 24" × 24" × 16"',
    colorScheme: 'Chocolate Brown (Duco)',
    modelNumber: 'TGV1',
    topType: 'Clean Gloss + Super Black & Golden Paint',
    finishing: 'High Gloss',
    dateAdded: '2026-05-17',
    salesRank: 4,
  },
  {
    id: 53,
    name: 'The Meander Square',
    badge: 'new',
    category: 'Coffee Tables',
    material: 'MDF + Fine Board (ZRK) with Fiber Molding Antique Gold Foot',
    description: "Crafted from premium MDF and Fine Board (ZRK) and elevated on ornate fiber molding feet with an antique gold finish, The Meander Square is a refined square coffee table of artisanal distinction. Its surface is finished in clean gloss with a super black and golden paint treatment, sealed beneath a silky matte lacquer that delivers the piece's signature smooth, luminous touch. Presented in a rich Chocolate Brown Duco colour scheme, this table measures 42\" (L) × 42\" (W) × 17\" (H) — a perfectly proportioned square silhouette that commands any distinguished living space with quiet, sovereign authority.",
    image: '/images/53.webp',
    images: ['https://ms-furniture-backend-production-0722.up.railway.app/images/e65f81de-b5eb-4909-a17d-e535517be98e.png'],
    sizing: '42" × 42" × 17" (L × W × H)',
    colorScheme: 'Chocolate Brown (Duco)',
    modelNumber: 'RT',
    topType: 'Clean Gloss + Super Black & Golden Paint',
    finishing: 'Silky Matte',
    dateAdded: '2026-05-17',
    salesRank: 10,
  },
  {
    id: 54,
    name: 'The Atrium Extension',
    badge: 'new',
    category: 'Coffee Tables',
    material: 'MDF + Fine Board (ZRK) with Fiber Molding Antique Gold Foot',
    description: "Crafted from premium MDF and Fine Board (ZRK) and elevated on ornate fiber molding feet with an antique gold finish, The Atrium Extension is a refined expression of artisanal luxury. Its surface is finished in clean gloss with a super black and golden paint treatment, sealed beneath a silky matte lacquer that delivers the piece's signature smooth, luminous touch. Presented in a rich Chocolate Brown Duco colour scheme, this table measures 48\" (L) × 30\" (W) × 17\" (H) — perfectly proportioned to anchor any distinguished living space with understated elegance and sovereign authority.",
    image: '/images/54.webp',
    sizing: '48" × 30" × 17" (L × W × H)',
    colorScheme: 'Chocolate Brown (Duco)',
    modelNumber: 'NS',
    topType: 'Clean Gloss + Super Black & Golden Paint',
    finishing: 'Silky Matte',
    dateAdded: '2026-05-17',
    salesRank: 1,
  },
  {
    id: 55,
    name: 'The Noir Labyrinth',
    badge: 'new',
    category: 'Coffee Tables',
    material: 'MDF + Fine Board (ZRK)',
    description: "Crafted from premium MDF and Fine Board (ZRK), The Noir Labyrinth is a refined expression of dark, artisanal sophistication. Its surface is finished in clean gloss with a super black and golden paint treatment, sealed beneath a silky matte lacquer that delivers the piece's signature smooth, luminous touch. Presented in a rich Chocolate Brown Duco colour scheme, this table measures 48\" (L) × 30\" (W) × 17\" (H) — perfectly proportioned to anchor any distinguished living space with understated elegance and quiet sovereign authority.",
    image: '/images/55.webp',
    sizing: '48" × 30" × 17" (L × W × H)',
    colorScheme: 'Chocolate Brown (Duco)',
    modelNumber: 'S2',
    topType: 'Clean Gloss + Super Black & Golden Paint',
    finishing: 'Silky Matte',
    dateAdded: '2026-05-17',
    salesRank: 11,
  },
  {
    id: 56,
    name: 'The Walnut Pavilion',
    badge: 'new',
    category: 'Coffee Tables',
    material: 'MDF + Fine Board (ZRK)',
    description: "Crafted from premium MDF and Fine Board (ZRK), The Walnut Pavilion is a refined square coffee table of artisanal distinction. Its surface is finished in clean gloss with a super black and golden paint treatment, sealed beneath a silky matte lacquer that delivers the piece's signature smooth, luminous touch. Presented in a rich Chocolate Brown Duco colour scheme, this table measures 36\" (L) × 36\" (W) × 17\" (H) — a perfectly proportioned square silhouette that commands any distinguished living space with quiet, sovereign authority.",
    image: '/images/56.webp',
    sizing: '36" × 36" × 17" (L × W × H)',
    colorScheme: 'Chocolate Brown (Duco)',
    modelNumber: 'WP',
    topType: 'Clean Gloss + Super Black & Golden Paint',
    finishing: 'Silky Matte',
    dateAdded: '2026-05-17',
    salesRank: 13,
  },
  {
    id: 59,
    name: 'The Versailles Cabriolet',
    badge: 'new',
    category: 'Coffee Tables',
    material: 'MDF + Fine Board (ZRK)',
    description: "Crafted from premium MDF and Fine Board (ZRK), The Versailles Cabriolet is a bold expression of dark, contemporary luxury. Its surface is finished in clean gloss with a super black and sparkel silver paint treatment, sealed beneath a brilliant high gloss lacquer that delivers a commanding, mirror-like depth. Featuring a heavy drawer design for practical elegance, this table is presented in a striking Black and Sparkel Silver Duco colour scheme and measures 48\" (L) × 30\" (W) × 17\" (H) — perfectly proportioned to anchor any distinguished living space with dramatic contrast and sovereign authority.",
    image: '/images/59.webp',
    sizing: '48" × 30" × 17" (L × W × H)',
    colorScheme: 'Black and Sparkel Silver With heavy Drawer (Duco)',
    modelNumber: 'VC',
    topType: 'Clean Gloss + Super Black & Sparkel Silver Paint',
    finishing: 'High Gloss',
    dateAdded: '2026-05-17',
    salesRank: 3,
  },
]

const BATCH4: Product[] = [
  {
    id: 60,
    name: 'Organic Walnut Coffee Table Set',
    badge: 'new',
    category: 'Coffee Sets',
    material: 'MDF + Fine Board (ZRK) With Fiber Molding Foot',
    description: 'Crafted from premium MDF and Fine Board (ZRK) with fiber molding foot, the Organic Walnut Coffee Table Set features a clean gloss finish with super black and golden paint. Finished in high gloss for a brilliant mirror-like depth in a Royal Golden High Gloss colour scheme, this set measures 48" (L) × 30" (W) × 17" (H) — a perfectly proportioned silhouette that anchors any distinguished living space with refined elegance.',
    image: '/images/60.webp',
    sizing: '48" × 30" × 17" (L × W × H)',
    colorScheme: 'Royal Golden High Gloss',
    modelNumber: 'NC',
    topType: 'Clean Gloss + Super Black & Golden Paint',
    finishing: 'High Gloss',
    dateAdded: '2026-05-26',
    salesRank: 29,
  },
  {
    id: 61,
    name: 'Royal Living Room Collection',
    badge: 'new',
    category: 'Coffee Tables',
    material: 'MDF + Fine Board (ZRK) With Imported Golden Chrome Foot',
    description: 'Crafted from premium MDF and Fine Board (ZRK) with imported golden chrome foot, the Royal Living Room Collection features a clean gloss super black painted top. Finished in high gloss with a White and Black High Gloss colour scheme, this set measures 36" (L) × 60" (W) × 17" (H) — a magnificent living collection that commands attention with regal sophistication.',
    image: '/images/61.webp',
    sizing: '36" × 60" × 17" (L × W × H)',
    colorScheme: 'White and Black High Gloss',
    modelNumber: 'GM',
    topType: 'Clean Gloss Super Black Paint',
    finishing: 'High Gloss',
    dateAdded: '2026-05-26',
    salesRank: 30,
  },
  {
    id: 62,
    name: 'White Marble & Gold Coffee Table',
    badge: 'new',
    category: 'Coffee Tables',
    material: 'MDF + Fine Board (ZRK)',
    description: 'Crafted from premium MDF and Fine Board (ZRK), the White Marble & Gold Coffee Table features a black and golden marbelized top. Finished in high gloss with a Black and Golden High Gloss (Duco) colour scheme, this table measures 48" (L) × 30" (W) × 17" (H) — a sophisticated statement piece that brings timeless elegance to any distinguished living space.',
    image: '/images/62.webp',
    sizing: '48" × 30" × 17" (L × W × H)',
    colorScheme: 'Black and Golden High Gloss (Duco)',
    modelNumber: 'C22',
    topType: 'Black & Golden Marbelize',
    finishing: 'High Gloss',
    dateAdded: '2026-05-26',
    salesRank: 31,
  },
  {
    id: 63,
    name: 'Heritage Carved Coffee Table',
    badge: 'new',
    category: 'Coffee Tables',
    material: 'MDF + Fine Board (ZRK) With Imported Metal Foot',
    description: 'Crafted from premium MDF and Fine Board (ZRK) with imported metal foot, the Heritage Carved Coffee Table features a clean gloss marbelized top. Finished in high gloss with a Royal Golden High Gloss colour scheme, this table measures 36" × 36" × 17" — a timeless carved masterpiece that anchors any distinguished living space with regal elegance.',
    image: '/images/63.webp',
    sizing: '36" × 36" × 17" (L × W × H)',
    colorScheme: 'Royal Golden High Gloss',
    modelNumber: 'Round M',
    topType: 'Clean Gloss + Marbelize',
    finishing: 'High Gloss',
    dateAdded: '2026-05-26',
    salesRank: 32,
  },
  {
    id: 64,
    name: 'Executive Dark Coffee Table',
    badge: 'new',
    category: 'Coffee Tables',
    material: 'Solid Wood & MDF',
    description: 'A bold executive-style coffee table set in deep espresso black with clean architectural lines. Shown alongside a matching dark sideboard cabinet, this piece brings a sophisticated, contemporary feel with a Lahore skyline-inspired setting.',
    image: '/images/64.webp',
    sizing: '60" × 32" × 19" (L × W × H)',
    colorScheme: 'Espresso Black',
    modelNumber: 'MS-CT-064',
    topType: 'Black Gloss',
    finishing: 'High Gloss',
    dateAdded: '2026-05-26',
    salesRank: 33,
  },
  {
    id: 65,
    name: 'Art Deco Living Set – Teal',
    badge: 'new',
    category: 'Coffee Tables',
    material: 'MDF + Fine Board (ZRK) With Fiber Molding Foot',
    description: 'Crafted from premium MDF and Fine Board (ZRK) with fiber molding foot, the Art Deco Living Set features a super black and golden paint top. Finished in high gloss with a Smoked Grey & Golden Black Antique colour scheme, this set measures 48" (L) × 30" (W) × 17" (H) — an exquisite Art Deco inspired piece that brings refined luxury to any distinguished living space.',
    image: '/images/65.webp',
    sizing: '48" × 30" × 17" (L × W × H)',
    colorScheme: 'Smoked Grey & Golden Black Antique',
    modelNumber: 'NC2',
    topType: 'Super Black & Golden Paint',
    finishing: 'High Gloss',
    dateAdded: '2026-05-26',
    salesRank: 34,
  },
  {
    id: 66,
    name: 'Pearl White Chesterfield Set – Round Table',
    badge: 'new',
    category: 'Coffee Tables',
    material: 'Leather & Marble',
    description: 'A sophisticated pearl white tufted Chesterfield living set paired with a round black marble-top center table on gold legs. Set against a dramatic city night skyline backdrop, exuding penthouse-level opulence.',
    image: '/images/66.webp',
    sizing: 'Custom',
    colorScheme: 'Pearl White & Black Gold',
    modelNumber: 'MS-LS-066',
    topType: 'Black Marble Round',
    finishing: 'High Gloss',
    dateAdded: '2026-05-26',
    salesRank: 35,
  },
  {
    id: 67,
    name: 'Luxury Tufted Sofa – Black Marble Table',
    badge: 'new',
    category: 'Coffee Tables',
    material: 'Leather & Sintered Stone',
    description: 'An ultra-luxurious living arrangement featuring deep-tufted champagne white leather sofas with a sleek black marble-top rectangular table with thin gold legs. The perfect embodiment of modern luxury with classic character.',
    image: '/images/67.webp',
    sizing: 'Custom',
    colorScheme: 'Champagne White & Black Marble',
    modelNumber: 'MS-LS-067',
    topType: 'Black Marble Rectangular',
    finishing: 'Gold Trim',
    dateAdded: '2026-05-26',
    salesRank: 36,
  },
  {
    id: 69,
    name: 'Modern Drum Coffee Table Set',
    badge: 'new',
    category: 'Coffee Sets',
    material: 'MDF + Fine Board (ZRK) With Fiber Molding Foot',
    description: 'Crafted from premium MDF and Fine Board (ZRK) with fiber molding foot, the Modern Drum Coffee Table Set features a clean gloss finish with super black and silver paint. Finished in high gloss with a Silver Grey & Black Antique colour scheme, this set measures 48" (L) × 30" (W) × 17" (H) — a sophisticated statement piece for any distinguished living space.',
    image: '/images/69.webp',
    sizing: '48" × 30" × 17" (L × W × H)',
    colorScheme: 'Silver Grey & Black Antique',
    modelNumber: 'NC1',
    topType: 'Clean Gloss Super Black & Silver Paint',
    finishing: 'High Gloss',
    dateAdded: '2026-05-26',
    salesRank: 38,
  },
]

const BATCH1_META: Record<number, { dateAdded: string; salesRank: number }> = {
  1: { dateAdded: '2026-05-10', salesRank: 4 },
  2: { dateAdded: '2026-05-10', salesRank: 6 },
  3: { dateAdded: '2026-05-10', salesRank: 2 },
  5: { dateAdded: '2026-05-10', salesRank: 1 },
  6: { dateAdded: '2026-05-10', salesRank: 3 },
  7: { dateAdded: '2026-05-10', salesRank: 7 },
  8: { dateAdded: '2026-05-10', salesRank: 5 },
  9: { dateAdded: '2026-05-10', salesRank: 9 },
  10: { dateAdded: '2026-05-10', salesRank: 8 },
  11: { dateAdded: '2026-05-10', salesRank: 12 },
  12: { dateAdded: '2026-05-10', salesRank: 11 },
  13: { dateAdded: '2026-05-10', salesRank: 14 },
  14: { dateAdded: '2026-05-10', salesRank: 13 },
  16: { dateAdded: '2026-05-10', salesRank: 15 },
  17: { dateAdded: '2026-05-10', salesRank: 18 },
  18: { dateAdded: '2026-05-10', salesRank: 17 },
  19: { dateAdded: '2026-05-10', salesRank: 20 },
  20: { dateAdded: '2026-05-10', salesRank: 19 },
  21: { dateAdded: '2026-05-10', salesRank: 22 },
  22: { dateAdded: '2026-05-10', salesRank: 21 },
  23: { dateAdded: '2026-05-10', salesRank: 24 },
  24: { dateAdded: '2026-05-10', salesRank: 23 },
  25: { dateAdded: '2026-05-10', salesRank: 26 },
  26: { dateAdded: '2026-05-10', salesRank: 25 },
  27: { dateAdded: '2026-05-10', salesRank: 28 },
  28: { dateAdded: '2026-05-10', salesRank: 27 },
}

export const ALL_PRODUCTS: Product[] = [
  ...BATCH1.map(p => ({ ...p, ...(BATCH1_META[p.id] || {}) })),
  ...BATCH2,
  ...BATCH3,
  ...BATCH4,
]

export const getNewArrivals = (limit = 12) =>
  [...ALL_PRODUCTS]
    .sort((a, b) => new Date(b.dateAdded || '').getTime() - new Date(a.dateAdded || '').getTime())
    .slice(0, limit)

export const getBestSellers = (limit = 12) =>
  [...ALL_PRODUCTS]
    .filter(p => p.salesRank != null)
    .sort((a, b) => (a.salesRank || 999) - (b.salesRank || 999))
    .slice(0, limit)

export const CATEGORIES = [
  { id: 'all', label: 'All' },
  { id: 'Coffee Tables', label: 'Coffee Tables' },
  { id: 'Coffee Sets', label: 'Coffee Sets' },
  { id: 'Sofa Set', label: 'Sofa Set' },
  { id: 'Bed Set', label: 'Bed Set' },
]
